# Generated by Django 4.2.2 on 2023-07-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('days', models.CharField(max_length=200)),
                ('details', models.CharField(default='description', max_length=500)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special', to='api.bar')),
            ],
        ),
    ]
