# Generated by Django 4.2.2 on 2023-07-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specials', to='api.bar'),
        ),
    ]
